### PR TITLE
fixed missing Jason.pch for XCode 5

### PR DESCRIPTION
**Pull request by gyulalaszlo**
The Jason.pch file is missing (at least for XCode 5). Removing it from the project seems to fix the problem.

Tested on OSX 10.9

### CODE REVIEW

**Comment by liuyuning** [comment]
Jason.app is not support macOS sierra(10.12), and some API deprecated. Please update the code. This is one of my favorite APP.

**Comment by tbrannam** [comment]
@liuyuning take a look at this release - I think the release you had before was using Apple's Garbage Collection Library - which is no longer available in macOS 10.12 - let me know if it works

https://github.com/tbrannam/Jason/releases/tag/v0.2.1

**Comment by liuyuning** [comment]
@tbrannam It's works partly, We can't paste JSON text to the JASON.

**Comment by tbrannam** [comment]
@gyulalaszlo i've manually merged this in with fixes in master
@liuyuning I've opened the issues page and created a note for clipboard issues.

**Pull request closed without merging**
